# Generated by Django 4.2.7 on 2025-11-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la sala')),
                ('capacidad', models.IntegerField(verbose_name='Capacidad máxima')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservada', 'Reservada'), ('mantencion', 'En Mantención')], default='disponible', max_length=20, verbose_name='Estado')),
                ('habilitada', models.BooleanField(default=True, verbose_name='Habilitada')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_persona', models.CharField(max_length=12, verbose_name='RUT')),
                ('fecha_hora_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de inicio')),
                ('fecha_hora_termino', models.DateTimeField(verbose_name='Fecha y Hora de término')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.sala', verbose_name='Sala Reservada')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
    ]
