# Generated by Django 4.2.7 on 2025-11-19 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sala',
            options={},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora_termino',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='rut_persona',
        ),
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(default='cliente@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='horas_contratadas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombre_cliente',
            field=models.CharField(default='Cliente Anónimo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sala',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miApp.sala'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sala',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
