# Generated by Django 4.2.7 on 2025-11-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_alter_reserva_options_alter_sala_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_creacion',
            new_name='fecha_hora_inicio',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='fecha_reserva',
            new_name='fecha_hora_termino',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='nombre_cliente',
            new_name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='horas_contratadas',
        ),
        migrations.AddField(
            model_name='reserva',
            name='rut_persona',
            field=models.CharField(default='11111111-1', max_length=12, verbose_name='RUT'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.CharField(default='disponible', max_length=20),
        ),
    ]
