# Generated by Django 4.2.7 on 2025-11-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='rut_persona',
            field=models.CharField(default='11111111-1', max_length=12, verbose_name='RUT'),
        ),
    ]
